language: node_js
node_js:
  - 11.13.0
script:
  - npm run build
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: product-admin-production
    region: eu-central-1
    acl: public_read
    local_dir: build
    on:
      branch: master

  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: $ACCESS-HEROKU_KEY
    app: products-admin-app
    local_dir: build
    on:
      branch: master
