language: node_js
node_js:
  - 11.13.0
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: product-admin-production
    region: eu-central-1
    acl: public_read
    on:
      branch: master
