language: node_js
node_js:
- 11.13.0
script:
- npm run build
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: "$ACCESS_KEY_ID"
    secret_access_key: "$SECRET_ACCESS_KEY"
    bucket: product-admin-production
    region: eu-central-1
    acl: public_read
    local_dir: build
    on:
      branch: master
  - provider: heroku
    skip_cleanup: true
    app: products-admin-app
    local_dir: build
    on:
      branch: master
    api_key:
      secure: oZXYkU5vJZ4mG0n89zBdDmE0nCYppqTeGPggeGYiQ0zbi7ker3GY1+HB2Se0sXEDYBPz1LfO6UyeLOsiv99iTdl+HXWvbiXRA/mmzjbsjAFc48q1SyGWtBHige8yEBgJx/ii6oSkBAgB+I5WlwkXnhLtFmXtO0DhxlCw6+jBI5uD8VJ9bypgysZFmSgZTSZ9zEQyDAN1rdAvvIlqsohvYmcNeziD8O5XWdv82lG6CKPjHecEgrLU/c4aTnVfZPRZCMSdoLgzmXzjl2VSB3GkiIQgyuOD/j/DauaWszIYOiF4CD5z0Sq3yrzl5XzK+xS6vpnv+eNGzUkWR3PLu5MlnLG9qVJ8q3HmcmPew9kWBqi0UeUJdmodA9tG5Mr7lH8yfltljMMr+kmG9/N1I8mBD1d8WuZTYwtfqg33ga+lbarshhbOhbF8jwPD1RH/O9CvkMu1v1iuBI1gayaHFZL/HlbeIMIn+Ims9ljgswU6B4cwMKKcBenNJwBZEDWTiTHhfOKfxGoGsbI7ONDNE+wFvCd9T34h6GD+NTmRRfhd1x3gIdnXJhz+jVtFWS8OA/VmyrA9BOkcDkhxlcBr83YA5rDopstmnH5mYWA+RFVv5WnyonLBrRMOwX4CDHjdp7YSgj828zqPmSclCkJyhKSO9opTMNhrJ/Jxy/WUonVwHvI=
